// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM_5ip1Vs5eZNB4lu3YbTWmyi_8kTvf58',
    appId: '1:420005704423:web:904a776f5e5daaef762842',
    messagingSenderId: '420005704423',
    projectId: 'doctor-app-b2371',
    authDomain: 'doctor-app-b2371.firebaseapp.com',
    storageBucket: 'doctor-app-b2371.firebasestorage.app',
    measurementId: 'G-6ENK5F2BWW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhisIonvsgDNRlGAOoPdTOx0nan74ejq4',
    appId: '1:420005704423:android:85d3c22bb7a89db9762842',
    messagingSenderId: '420005704423',
    projectId: 'doctor-app-b2371',
    storageBucket: 'doctor-app-b2371.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxNMS0mbSbzcfOuvBxn1aiC_MGoCKl4z8',
    appId: '1:420005704423:ios:6f2a2eb82d1db5b2762842',
    messagingSenderId: '420005704423',
    projectId: 'doctor-app-b2371',
    storageBucket: 'doctor-app-b2371.firebasestorage.app',
    iosBundleId: 'com.example.careConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxNMS0mbSbzcfOuvBxn1aiC_MGoCKl4z8',
    appId: '1:420005704423:ios:6f2a2eb82d1db5b2762842',
    messagingSenderId: '420005704423',
    projectId: 'doctor-app-b2371',
    storageBucket: 'doctor-app-b2371.firebasestorage.app',
    iosBundleId: 'com.example.careConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBM_5ip1Vs5eZNB4lu3YbTWmyi_8kTvf58',
    appId: '1:420005704423:web:c3993929f90c2241762842',
    messagingSenderId: '420005704423',
    projectId: 'doctor-app-b2371',
    authDomain: 'doctor-app-b2371.firebaseapp.com',
    storageBucket: 'doctor-app-b2371.firebasestorage.app',
    measurementId: 'G-QTY7NZFT25',
  );
}
